version: '3'

services:
  jenkins:
    build:
      context: ./docker
      dockerfile: Jenkins.Dockerfile
    ports:
      - "9000:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  jenkins_home:

#  web:
#    build:
#      context: ./docker
#      dockerfile: Dockerfile
#    ports:
#    - "8080:8080"
#    volumes:
#    - .:/home/gradle/app
#    command: [gradle, bootRun]

